const $=id=>document.getElementById(id);const messages=$('messages'),input=$('question');let previousId=null,busy=false,epoch=0;const counts={questions:0,found:0,handoffs:0};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function flow(n){for(let i=1;i<=4;i++)$('flow-'+i).classList.toggle('active',i<=n);}
function inspect(a,b,c){$('decision').textContent=a;$('confidence').textContent=b;$('source').textContent=c;}
function message(text,bot=true){const el=document.createElement('article');el.className='message';el.innerHTML=`<div class="avatar ${bot?'bot':'user'}">${bot?'K':'HV'}</div><div class="message-body"><div class="message-meta"><strong>${bot?'Trợ lý Kute':'Học viên'}</strong><time>${new Date().toLocaleTimeString('vi-VN')}</time></div><div class="message-text">${esc(text)}</div></div>`;messages.append(el);messages.scrollTop=messages.scrollHeight;return el.querySelector('.message-body');}
async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw new Error(result.error||'Không kết nối được máy chủ.');return result;}
async function ask(raw){const question=raw.trim();if(!question||busy)return;busy=true;const current=epoch;document.querySelector('.send').disabled=true;input.value='';message(question,false);flow(2);inspect('ĐANG TRA CỨU','…','…');const loading=message('Đang đối chiếu nguồn và xử lý câu hỏi…');
 try{const a=await api('/api/ask',{question,previousId});if(current!==epoch)return;previousId=a.id;loading.parentElement.remove();counts.questions++;if(a.decision==='FOUND')counts.found++;$('question-count').textContent=counts.questions;$('found-count').textContent=counts.found;inspect(a.decision,a.mode,a.sources.map(s=>s.id).join(', ')||'—');flow(3);const el=message(a.answer);const detail=document.createElement('div');detail.className=`answer ${a.decision.toLowerCase().replace('_','-')}`;detail.innerHTML=`<div class="answer-head"><span class="badge ${a.decision.toLowerCase().replace('_','-')}">${esc(a.decision)}</span><span class="confidence">${esc(a.mode)} · ${a.latencyMs??0} ms</span></div>`;
 for(const s of a.sources){const box=document.createElement('details');box.innerHTML=`<summary>${esc(s.id)} · ${esc(s.title)}</summary><p>${esc(s.authority)} · ${esc(s.date)}</p><p>${esc(s.excerpt)}</p><a class="source" href="/api/sources/${encodeURIComponent(s.id)}" target="_blank" rel="noopener">Mở trích đoạn gốc ${esc(s.id)}</a>`;detail.append(box);}
 const actions=document.createElement('div');actions.className='answer-actions';for(const [label,action] of [['Đã giải quyết','solved'],['Chuyển TA','ticket'],['Câu trả lời chưa đúng','incorrect']]){const b=document.createElement('button');b.className='action';b.textContent=label;b.onclick=async()=>{b.disabled=true;try{if(action==='ticket'){const t=await api('/api/tickets',{id:a.id});message(t.message);counts.handoffs++;$('handoff-count').textContent=counts.handoffs;if(t.state!=='sent')b.disabled=false;}else{await api('/api/feedback',{id:a.id,value:action});message(action==='solved'?'Đã lưu xác nhận giải quyết.':'Đã lưu phản hồi chưa đúng. Bạn có thể bổ sung thông tin hoặc chuyển TA.');}flow(4);}catch(e){message(e.message);b.disabled=false;}};actions.append(b);}detail.append(actions);el.append(detail);messages.scrollTop=messages.scrollHeight;
 }catch(e){if(current===epoch){loading.parentElement.remove();message(`Không thể xử lý: ${e.message}`);inspect('ERROR','—','—');}}finally{busy=false;document.querySelector('.send').disabled=false;input.focus();}}
function resetChat(){epoch++;previousId=null;messages.replaceChildren();flow(1);inspect('READY','—','—');message('Chào bạn! Mình hỗ trợ lỗi CVAT và truy cập Phoenix, kèm trích đoạn nguồn để bạn kiểm tra. Hãy nêu bước gặp lỗi và thông báo lỗi. Quy định khóa học chưa có nguồn chính thức sẽ cần TA xác minh. Không gửi mật khẩu hoặc token.');}
window.resetChat=resetChat;$('question-form').addEventListener('submit',e=>{e.preventDefault();ask(input.value)});input.maxLength=2000;document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{input.value=b.dataset.q;input.focus();});document.querySelectorAll('.channel').forEach(b=>{b.disabled=true;b.title='Kênh minh họa; dùng /hoi trong Discord sau khi cấu hình bot.';});messages.setAttribute('aria-live','polite');resetChat();fetch('/api/health').then(r=>r.json()).then(h=>document.querySelector('.status').textContent=`● AI ${h.ai?'đã cấu hình':'chưa cấu hình'} · Discord ${h.discord?'đã cấu hình':'chưa kết nối'}`).catch(()=>document.querySelector('.status').textContent='● Máy chủ chưa kết nối');
