// Curated excerpts, not all chat messages. Roles in the anonymized pack are unknown.
export const knowledge = [
 {id:'M12802',title:'CVAT · OPA health check lúc khởi động',topics:['cvat','opa','docker'],terms:['500','bundle','health','migration','compose','working'],excerpt:'Ngay sau docker compose up -d, OPA chưa lấy được policy bundle từ cvat-server, nên health check báo: 500 ... http://opa:8181/health?bundles. Sau khoảng một phút, CVAT server hoàn tất migration; OPA tải bundle thành công và lần health check tiếp theo báo toàn bộ working.',answer:'Nếu OPA báo 500 ở /health?bundles ngay sau docker compose up -d, chờ khoảng một phút để CVAT hoàn tất migration rồi kiểm tra lại.',date:'2026-09-12–14',authority:'Trao đổi cộng đồng, chưa xác minh vai trò TA'},
 {id:'M29806',title:'CVAT · lệnh kiểm tra sức khỏe',topics:['cvat','docker'],terms:['health','kiem tra','lenh','compose','working'],excerpt:'cd ~/Projects/cvat-day2\nsleep 45\ndocker exec -t cvat_server python manage.py health_check',answer:'Trong môi trường CVAT của bài thực hành, chờ 45 giây rồi chạy: docker exec -t cvat_server python manage.py health_check. Nếu vẫn lỗi, gửi output (che thông tin riêng) cho TA.',date:'2026-09-12–14',authority:'Trao đổi cộng đồng, chưa xác minh vai trò TA'},
 {id:'M17439',title:'CVAT · phiên bản trong bài thực hành',topics:['cvat','opa'],terms:['version','phien ban','tag','image','cu','1.12.2','2.74.1'],excerpt:'hình bản của bạn là ver cũ tag chuẩn CVAT v2.74.1 dùng openpolicyagent/opa:1.12.2.',answer:'Trao đổi trong dữ liệu onboarding nhắc CVAT v2.74.1 và openpolicyagent/opa:1.12.2. Đối chiếu tài liệu bài hiện tại trước khi thay đổi phiên bản.',date:'2026-09-12–14',authority:'Trao đổi cộng đồng, chưa xác minh vai trò TA'},
 {id:'M28576',title:'Phoenix · đường dẫn đăng nhập',topics:['phoenix'],terms:['link','mail','dang nhap','truy cap','vao'],excerpt:'vào đúng link trong thông báo nhé không phải link trong mail nha',answer:'Kiểm tra lại link trong thông báo của chương trình thay vì link trong email. Bộ dữ liệu không giữ đường dẫn đầy đủ; nếu vẫn không vào được, cần TA kiểm tra.',date:'2026-09-12–14',authority:'Trao đổi cộng đồng, chưa xác minh vai trò TA'}
];
export const normalize = s => s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
export function retrieve(question){const q=normalize(question);return knowledge.map(d=>({ ...d,score:d.topics.some(t=>q.includes(t))?d.terms.reduce((n,t)=>n+(q.includes(t)?1:0),0)+1:0})).filter(d=>d.score>=2).sort((a,b)=>b.score-a.score).slice(0,3);}

